import suffix from "./suffixRoute";

export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  detail: `detail/${suffix.detailId}`,
  cart: "/cart",
  userProfile: "/user",
  userChangePassword: "/change-password",
  userAddress: "/address",
  maintenance: "/maintenance",
  orderManagement: "/order-management",
  favoriteProduct: "/favorite-product",
  notFound: "notFound",
  paymentSuccessfull: "/payment-successfull",
  news: "/news",
  newsDetail: `/news/${suffix.detailId}`,
  productList: "/product-list",
  productDetail: `/product-list/product-detail/${suffix.detailId}`,
  aboutUs: "/about-us",
  privacyPolicy: "/privacy-policy",
  termsOfService: "/terms-of-service",
};

export const adminRoutes = {
  dashboard: "/dashboard",
  user: "/dashboard/user",
  userDetail: "/dashboard/userDetail/:id",
  accountDetail: "/dashboard/accountDetail/:id",
  blogs: "/dashboard/news",
  blog: `/dashboard/news/${suffix.detailId}`,
  createNew: "/dashboard/create/news",
  editNew: `/dashboard/edit/news/${suffix.detailId}`,
  newsCategory: `/dashboard/newsCategory`,
  product: "/dashboard/product",
  createProduct: "/dashboard/create/product",
  viewDetailProduct: "/dashboard/product/:id",
  viewSerialProduct: "/dashboard/product/serial/:id",
  profile: "/dashboard/user/account",
  category: "/dashboard/categories",
  brand: "/dashboard/brand",
  order: "/dashboard/orders",
  rank: "/dashboard/ranks",
  maintenance: "/dashboard/maintenance",
};
